/**
 * Access to the imported 360° spin sets.
 *
 * src/data/spins.json is generated by scripts/build-spins.mjs from the
 * photography project's pieces.json. Adding a piece means dropping a folder
 * in that project, adding its manifest entry, and rerunning the script —
 * nothing here or in any layout changes.
 */
import data from '../data/spins.json';

export interface SpinRecord {
  id: string;
  /** The photographer's working name. Not for display; pieces carry real titles. */
  workingName: string;
  count: number;
  shot: string;
  /** True rotation angle of each frame, in degrees. Always present. */
  angles: number[];
  /** False where the shoot could not be measured and even spacing was assumed. */
  anglesMeasured: boolean;
  anglesNote: string | null;
  /** Some pieces cannot be cut out and can only ever appear on their linen ground. */
  hasCutout: boolean;
  sizes: Record<string, number>;
  base: string;
  palette: { deep: string; mid: string; light: string; accent: string; linen: string };
  caveats: string[];
  source: { frames: string; cutout: string | null };
}

export const spinLibrary = data.spins as SpinRecord[];

export function getSpinRecord(id?: string | null): SpinRecord | undefined {
  if (!id) return undefined;
  return spinLibrary.find((s) => s.id === id);
}

/** What the browser runtime needs, as small as it can be made. */
export interface SpinSpec {
  id: string;
  base: string;
  variant: 'w' | 'd' | 'c';
  count: number;
  angles: number[];
}

export function spinSpec(record: SpinRecord, variant: SpinSpec['variant']): SpinSpec {
  return {
    id: record.id,
    base: record.base,
    variant,
    count: record.count,
    angles: record.angles,
  };
}

/** Path to a single frame, for the one frame a tile ships in its markup. */
export function framePath(record: SpinRecord, variant: SpinSpec['variant'], index = 0): string {
  return `${record.base}/${variant}/${String(index).padStart(2, '0')}.webp`;
}

/**
 * CSS custom properties carrying a piece's own glaze, so a page can pick up
 * the colour of the pot it is showing. Sampled from the fired surface.
 */
export function paletteVars(record: SpinRecord | undefined): string | undefined {
  if (!record) return undefined;
  const p = record.palette;
  return [
    `--piece-accent:${p.deep}`,
    `--piece-mid:${p.mid}`,
    `--piece-light:${p.light}`,
    `--piece-linen:${p.linen}`,
  ].join(';');
}
