/**
 * Access to the imported 360° spin sets.
 *
 * src/data/spins.json is generated by scripts/build-spins.mjs from the
 * photography project's pieces.json. Adding a piece means dropping a folder
 * in that project, adding its manifest entry, and rerunning the script —
 * nothing here or in any layout changes.
 */
import data from '../data/spins.json';

export interface SpinRecord {
  id: string;
  /** The photographer's working name. Not for display; pieces carry real titles. */
  workingName: string;
  count: number;
  shot: string;
  /** True rotation angle of each frame, in degrees. Always present. */
  angles: number[];
  /** False where the shoot could not be measured and even spacing was assumed. */
  anglesMeasured: boolean;
  anglesNote: string | null;
  /** Widths actually built for this piece, ascending. Never upscaled. */
  widths: number[];
  /** The master's own size — the ceiling of what the camera resolved. */
  masterPx: number;
  base: string;
  palette: { deep: string; mid: string; light: string; accent: string; linen: string };
  caveats: string[];
  source: { frames: string };
}

export const spinLibrary = data.spins as SpinRecord[];

export function getSpinRecord(id?: string | null): SpinRecord | undefined {
  if (!id) return undefined;
  return spinLibrary.find((s) => s.id === id);
}

/** What the browser runtime needs, as small as it can be made. */
export interface SpinSpec {
  id: string;
  base: string;
  count: number;
  angles: number[];
  /** Ascending. The runtime picks one by measuring how big the piece is drawn. */
  widths: number[];
  /** Largest width this context may load, to bound decoded memory. */
  cap: number;
}

/**
 * @param cap Largest width worth loading here. A wall of spinning pieces is
 *   capped low because decoded frames, not downloads, are what runs a browser
 *   out of memory; a single piece on its own page can afford much more.
 */
export function spinSpec(record: SpinRecord, cap: number): SpinSpec {
  return {
    id: record.id,
    base: record.base,
    count: record.count,
    angles: record.angles,
    widths: record.widths,
    cap,
  };
}

/** Path to one frame at one width. */
export function framePath(record: SpinRecord, width: number, index = 0): string {
  return `${record.base}/${width}/${String(index).padStart(2, '0')}.webp`;
}

/** The widest built size not above a ceiling. */
export function widthUpTo(record: SpinRecord, ceiling: number): number {
  const fit = record.widths.filter((w) => w <= ceiling);
  return fit.length ? fit[fit.length - 1] : record.widths[0];
}

/**
 * A srcset across every built width, so the browser picks for the screen it is
 * actually on. Paired with a `sizes` hint describing how wide the image is
 * drawn, this is what makes one frame look right on a phone and on a 4K panel.
 */
export function frameSrcSet(record: SpinRecord, index = 0): string {
  return record.widths.map((w) => `${framePath(record, w, index)} ${w}w`).join(', ');
}

/**
 * CSS custom properties carrying a piece's own glaze, so a page can pick up
 * the colour of the pot it is showing. Sampled from the fired surface.
 */
export function paletteVars(record: SpinRecord | undefined): string | undefined {
  if (!record) return undefined;
  const p = record.palette;
  return [
    `--piece-accent:${p.deep}`,
    `--piece-mid:${p.mid}`,
    `--piece-light:${p.light}`,
    `--piece-linen:${p.linen}`,
  ].join(';');
}
