#!/usr/bin/env node
/**
 * Cut bands of real glaze out of the full-resolution photographs.
 *
 *   node scripts/make-glaze.mjs [--source ../]
 *
 * These are used as material in the page itself — a strip of surface between
 * sections, a header on the commissions page. Nothing here is rendered,
 * generated or approximated: each band is a crop of the actual fired surface at
 * the resolution the camera caught it. That is the whole point. A painted
 * approximation of a glaze on a site selling that glaze would be a lie, and it
 * would look like one.
 *
 * Adding a piece is a row in BANDS below. Pick the crop off its focus-stacked
 * frame in `<shoot>/merged/`, staying inside the glaze wall: below the rim,
 * above the foot, clear of the background. Run this, then reference the id.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const flagIndex = args.indexOf('--source');
const source = path.resolve(root, flagIndex === -1 ? '..' : args[flagIndex + 1]);

/**
 * Each band: where it comes from, and the window onto the glaze.
 * Crops are in the merged frame's own full-resolution pixels (5472 x 3648).
 */
const BANDS = [
  {
    id: 'celadon',
    piece: 'celadon-cup',
    frame: 'spin-cup/merged/pos01.jpg',
    // The wall of the cup, through the run of the drip.
    crop: { left: 1850, top: 1700, width: 1700, height: 620 },
    note: 'Celadon cup — crystalline break with a single drip',
  },
];

/** Widths served. The band is decorative and full-bleed, so it wants width. */
const WIDTHS = [900, 1700];

async function main() {
  const outDir = path.join(root, 'public', 'images', 'glaze');
  await mkdir(outDir, { recursive: true });
  const made = [];

  for (const band of BANDS) {
    const src = path.join(source, band.frame);
    if (!existsSync(src)) {
      console.warn(`  ! ${band.id}: no source at ${src} — skipped`);
      continue;
    }
    const meta = await sharp(src).metadata();
    const max = Math.min(band.crop.width, meta.width - band.crop.left);
    if (max < band.crop.width) {
      throw new Error(`${band.id}: crop runs past the right edge of ${band.frame}`);
    }

    const widths = WIDTHS.filter((w) => w <= band.crop.width);
    for (const w of widths) {
      const out = path.join(outDir, `${band.id}-${w}.webp`);
      await sharp(src)
        .extract(band.crop)
        .resize(w)
        .webp({ quality: 88, effort: 5 })
        .toFile(out);
    }
    made.push({
      id: band.id,
      piece: band.piece,
      note: band.note,
      widths,
      aspect: Math.round((band.crop.width / band.crop.height) * 1000) / 1000,
      source: band.frame,
    });
    console.log(`  ${band.id}: ${widths.join(', ')}px from ${band.frame}`);
  }

  await writeFile(
    path.join(root, 'src', 'data', 'glaze.json'),
    JSON.stringify(
      {
        $comment: 'Generated by scripts/make-glaze.mjs. Real glaze, cropped from the photographs.',
        bands: made,
      },
      null,
      2
    ) + '\n'
  );
  console.log(`Wrote src/data/glaze.json — ${made.length} band(s)`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
